src/Entity/Seances.php
<?php

namespace App\Entity;

use App\Repository\SeancesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SeancesRepository::class)]
class Seances
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_seance = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_debut = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_fin = null;

    #[ORM\ManyToOne(inversedBy: 'seances')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Salles $id_salle = null;

    #[ORM\ManyToOne(inversedBy: 'seances')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Films $id_film = null;

    /**
     * @var Collection<int, Reservations>
     */
    #[ORM\OneToMany(targetEntity: Reservations::class, mappedBy: 'id_seance')]
    private Collection $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateSeance(): ?\DateTimeInterface
    {
        return $this->date_seance;
    }

    public function setDateSeance(\DateTimeInterface $date_seance): static
    {
        $this->date_seance = $date_seance;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(\DateTimeInterface $heure_debut): static
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }

    public function setHeureFin(\DateTimeInterface $heure_fin): static
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }

    public function getIdSalle(): ?Salles
    {
        return $this->id_salle;
    }

    public function setIdSalle(?Salles $id_salle): static
    {
        $this->id_salle = $id_salle;

        return $this;
    }

    public function getIdFilm(): ?Films
    {
        return $this->id_film;
    }

    public function setIdFilm(?Films $id_film): static
    {
        $this->id_film = $id_film;

        return $this;
    }

    /**
     * @return Collection<int, Reservations>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservations $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setIdSeance($this);
        }

        return $this;
    }

    public function removeReservation(Reservations $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getIdSeance() === $this) {
                $reservation->setIdSeance(null);
            }
        }

        return $this;
    }
}

src/Form/SeancesType.php
<?php

namespace App\Form;

use App\Entity\Films;
use App\Entity\Salles;
use App\Entity\Seances;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SeancesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_seance', null, [
                'widget' => 'single_text',
            ])
            ->add('heure_debut', null, [
                'widget' => 'single_text',
            ])
            ->add('heure_fin', null, [
                'widget' => 'single_text',
            ])
            ->add('id_salle', EntityType::class, [
                'class' => Salles::class,
                'choice_label' => 'id',
            ])
            ->add('id_film', EntityType::class, [
                'class' => Films::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Seances::class,
        ]);
    }
}

src/Controller/SeancesController.php
<?php

namespace App\Controller;

use App\Entity\Seances;
use App\Form\SeancesType;
use App\Repository\SeancesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/seances')]
final class SeancesController extends AbstractController
{
    #[Route(name: 'app_seances_index', methods: ['GET'])]
    public function index(SeancesRepository $seancesRepository): Response
    {
        return $this->render('seances/index.html.twig', [
            'seances' => $seancesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_seances_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $seance = new Seances();
        $form = $this->createForm(SeancesType::class, $seance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($seance);
            $entityManager->flush();

            return $this->redirectToRoute('app_seances_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('seances/new.html.twig', [
            'seance' => $seance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_seances_show', methods: ['GET'])]
    public function show(Seances $seance): Response
    {
        return $this->render('seances/show.html.twig', [
            'seance' => $seance,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_seances_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Seances $seance, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SeancesType::class, $seance);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_seances_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('seances/edit.html.twig', [
            'seance' => $seance,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_seances_delete', methods: ['POST'])]
    public function delete(Request $request, Seances $seance, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$seance->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($seance);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_seances_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/seances/_delete_form.html.twig
<form method="post" action="{{ path('app_seances_delete', {'id': seance.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ seance.id) }}">
    <button class="btn">Delete</button>
</form>

templates/seances/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/seances/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Seances{% endblock %}

{% block body %}
    <h1>Edit Seances</h1>

    {{ include('seances/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_seances_index') }}">back to list</a>

    {{ include('seances/_delete_form.html.twig') }}
{% endblock %}

templates/seances/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Seances index{% endblock %}

{% block body %}
    <h1>Seances index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_seance</th>
                <th>Heure_debut</th>
                <th>Heure_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for seance in seances %}
            <tr>
                <td>{{ seance.id }}</td>
                <td>{{ seance.dateSeance ? seance.dateSeance|date('Y-m-d') : '' }}</td>
                <td>{{ seance.heureDebut ? seance.heureDebut|date('H:i:s') : '' }}</td>
                <td>{{ seance.heureFin ? seance.heureFin|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_seances_show', {'id': seance.id}) }}">show</a>
                    <a href="{{ path('app_seances_edit', {'id': seance.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_seances_new') }}">Create new</a>
{% endblock %}

templates/seances/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Seances{% endblock %}

{% block body %}
    <h1>Create new Seances</h1>

    {{ include('seances/_form.html.twig') }}

    <a href="{{ path('app_seances_index') }}">back to list</a>
{% endblock %}

templates/seances/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Seances{% endblock %}

{% block body %}
    <h1>Seances</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ seance.id }}</td>
            </tr>
            <tr>
                <th>Date_seance</th>
                <td>{{ seance.dateSeance ? seance.dateSeance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Heure_debut</th>
                <td>{{ seance.heureDebut ? seance.heureDebut|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Heure_fin</th>
                <td>{{ seance.heureFin ? seance.heureFin|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_seances_index') }}">back to list</a>

    <a href="{{ path('app_seances_edit', {'id': seance.id}) }}">edit</a>

    {{ include('seances/_delete_form.html.twig') }}
{% endblock %}