src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    private ?Reservations $id_reservation = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $note = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $Commentaire = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_avis = null;

    #[ORM\Column]
    private ?bool $validation_avis = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdReservation(): ?Reservations
    {
        return $this->id_reservation;
    }

    public function setIdReservation(?Reservations $id_reservation): static
    {
        $this->id_reservation = $id_reservation;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->Commentaire;
    }

    public function setCommentaire(?string $Commentaire): static
    {
        $this->Commentaire = $Commentaire;

        return $this;
    }

    public function getDateAvis(): ?\DateTimeInterface
    {
        return $this->date_avis;
    }

    public function setDateAvis(\DateTimeInterface $date_avis): static
    {
        $this->date_avis = $date_avis;

        return $this;
    }

    public function isValidationAvis(): ?bool
    {
        return $this->validation_avis;
    }

    public function setValidationAvis(bool $validation_avis): static
    {
        $this->validation_avis = $validation_avis;

        return $this;
    }
}

src/Form/AvisType.php
<?php

namespace App\Form;

use App\Entity\Avis;
use App\Entity\Reservations;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('note', ChoiceType::class, [
                'choices' => [0, 1, 2, 3, 4, 5]

            ])
            ->add('Commentaire')
            //->add('date_avis', null, [
            //  'widget' => 'single_text',
            //])
            ->add('validation_avis')
            ->add('id_reservation', EntityType::class, [
                'class' => Reservations::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Avis::class,
        ]);
    }
}

src/Controller/AvisController.php
<?php

namespace App\Controller;

use App\Entity\Avis;
use App\Form\AvisType;
use App\Repository\AvisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


#[Route('/avis')]
final class AvisController extends AbstractController
{
    #[Route(name: 'app_avis_index', methods: ['GET'])]
    public function index(AvisRepository $avisRepository): Response
    {
        return $this->render('avis/index.html.twig', [
            'avis' => $avisRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_avis_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $avi = new Avis();
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $entityManager->persist($avi);
            $entityManager->flush();

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/new.html.twig', [
            'avi' => $avi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avis_show', methods: ['GET'])]
    public function show(Avis $avi): Response
    {
        return $this->render('avis/show.html.twig', [
            'avi' => $avi,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_avis_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Avis $avi, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/edit.html.twig', [
            'avi' => $avi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avis_delete', methods: ['POST'])]
    public function delete(Request $request, Avis $avi, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $avi->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($avi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/avis/_delete_form.html.twig
<form method="post" action="{{ path('app_avis_delete', {'id': avi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ avi.id) }}">
    <button class="btn">Delete</button>
</form>

templates/avis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/avis/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Avis{% endblock %}

{% block body %}
    <h1>Edit Avis</h1>

    {{ include('avis/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_avis_index') }}">back to list</a>

    {{ include('avis/_delete_form.html.twig') }}
{% endblock %}

templates/avis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis index{% endblock %}

{% block body %}
    <h1>Avis index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Note</th>
                <th>Commentaire</th>
                <th>Date_avis</th>
                <th>Validation_avis</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for avi in avis %}
            <tr>
                <td>{{ avi.id }}</td>
                <td>{{ avi.note }}</td>
                <td>{{ avi.Commentaire }}</td>
                <td>{{ avi.dateAvis ? avi.dateAvis|date('Y-m-d') : '' }}</td>
                <td>{{ avi.validationAvis ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_avis_show', {'id': avi.id}) }}">show</a>
                    <a href="{{ path('app_avis_edit', {'id': avi.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_avis_new') }}">Create new</a>
{% endblock %}

templates/avis/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Avis{% endblock %}

{% block body %}
    <h1>Create new Avis</h1>

    {{ include('avis/_form.html.twig') }}

    <a href="{{ path('app_avis_index') }}">back to list</a>
{% endblock %}

templates/avis/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis{% endblock %}

{% block body %}
    <h1>Avis</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ avi.id }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ avi.note }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ avi.Commentaire }}</td>
            </tr>
            <tr>
                <th>Date_avis</th>
                <td>{{ avi.dateAvis ? avi.dateAvis|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Validation_avis</th>
                <td>{{ avi.validationAvis ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_avis_index') }}">back to list</a>

    <a href="{{ path('app_avis_edit', {'id': avi.id}) }}">edit</a>

    {{ include('avis/_delete_form.html.twig') }}
{% endblock %}