src/Entity/Cinemas.php
<?php

namespace App\Entity;

use App\Repository\CinemasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CinemasRepository::class)]
class Cinemas
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_cinema = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $numero_gsm = null;

    #[ORM\Column(length: 500)]
    private ?string $Horaires = null;

    /**
     * @var Collection<int, Salles>
     */
    #[ORM\OneToMany(targetEntity: Salles::class, mappedBy: 'id_cinema')]
    private Collection $salles;

    public function __construct()
    {
        $this->salles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCinema(): ?string
    {
        return $this->nom_cinema;
    }

    public function setNomCinema(string $nom_cinema): static
    {
        $this->nom_cinema = $nom_cinema;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getNumeroGsm(): ?string
    {
        return $this->numero_gsm;
    }

    public function setNumeroGsm(string $numero_gsm): static
    {
        $this->numero_gsm = $numero_gsm;

        return $this;
    }

    public function getHoraires(): ?string
    {
        return $this->Horaires;
    }

    public function setHoraires(string $Horaires): static
    {
        $this->Horaires = $Horaires;

        return $this;
    }

    /**
     * @return Collection<int, Salles>
     */
    public function getSalles(): Collection
    {
        return $this->salles;
    }

    public function addSalle(Salles $salle): static
    {
        if (!$this->salles->contains($salle)) {
            $this->salles->add($salle);
            $salle->setId_Cinema($this);
        }

        return $this;
    }

    public function removeSalle(Salles $salle): static
    {
        if ($this->salles->removeElement($salle)) {
            // set the owning side to null (unless already changed)
            if ($salle->getId_Cinema() === $this) {
                $salle->setId_Cinema(null);
            }
        }

        return $this;
    }
}

src/Entity/Salles.php
<?php

namespace App\Entity;

use App\Repository\SallesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SallesRepository::class)]
class Salles
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'salles')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cinemas $id_cinema = null;

    #[ORM\Column(length: 255)]
    private ?string $qualite_projection = null;

    /**
     * @var Collection<int, Places>
     */
    #[ORM\OneToMany(targetEntity: Places::class, mappedBy: 'id_salle')]
    private Collection $places;

    /**
     * @var Collection<int, Seances>
     */
    #[ORM\OneToMany(targetEntity: Seances::class, mappedBy: 'id_salle')]
    private Collection $seances;

    public function __construct()
    {
        $this->places = new ArrayCollection();
        $this->seances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getId_Cinema(): ?Cinemas
    {
        return $this->id_cinema;
    }

    public function getIdCinema(): ?Cinemas
    {
        return $this->id_cinema;
    }

    public function setIdCinema(?Cinemas $id_cinema): static
    {
        $this->id_cinema = $id_cinema;

        return $this;
    }

    public function getQualiteProjection(): ?string
    {
        return $this->qualite_projection;
    }

    public function setQualiteProjection(string $qualite_projection): static
    {
        $this->qualite_projection = $qualite_projection;

        return $this;
    }

    /**
     * @return Collection<int, Places>
     */
    public function getPlaces(): Collection
    {
        return $this->places;
    }

    public function addPlace(Places $place): static
    {
        if (!$this->places->contains($place)) {
            $this->places->add($place);
            $place->setIdSalle($this);
        }

        return $this;
    }

    public function removePlace(Places $place): static
    {
        if ($this->places->removeElement($place)) {
            // set the owning side to null (unless already changed)
            if ($place->getIdSalle() === $this) {
                $place->setIdSalle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Seances>
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }

    public function addSeance(Seances $seance): static
    {
        if (!$this->seances->contains($seance)) {
            $this->seances->add($seance);
            $seance->setIdSalle($this);
        }

        return $this;
    }

    public function removeSeance(Seances $seance): static
    {
        if ($this->seances->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getIdSalle() === $this) {
                $seance->setIdSalle(null);
            }
        }

        return $this;
    }
}

src/Form/SallesType.php
<?php

namespace App\Form;

use App\Entity\Cinemas;
use App\Entity\Salles;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SallesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('qualite_projection', ChoiceType::class, [
                'choices' => [
                    '4K' => '4K',
                    'HD' => 'HD'
                ]

            ])
            ->add('id_cinema', EntityType::class, [
                'class' => Cinemas::class,
                'choice_label' => 'nom_cinema',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Salles::class,
        ]);
    }
}

src/Controller/SallesController.php
<?php

namespace App\Controller;

use App\Entity\Salles;
use App\Form\SallesType;
use App\Repository\SallesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/salles')]
final class SallesController extends AbstractController
{
    #[Route(name: 'app_salles_index', methods: ['GET'])]
    public function index(SallesRepository $sallesRepository): Response
    {
        return $this->render('salles/index.html.twig', [
            'salles' => $sallesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_salles_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $salle = new Salles();
        $form = $this->createForm(SallesType::class, $salle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($salle);
            $entityManager->flush();

            return $this->redirectToRoute('app_salles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('salles/new.html.twig', [
            'salle' => $salle,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_salles_show', methods: ['GET'])]
    public function show(Salles $salle): Response
    {
        return $this->render('salles/show.html.twig', [
            'salle' => $salle,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_salles_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Salles $salle, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SallesType::class, $salle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_salles_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('salles/edit.html.twig', [
            'salle' => $salle,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_salles_delete', methods: ['POST'])]
    public function delete(Request $request, Salles $salle, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $salle->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($salle);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_salles_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/salles/_delete_form.html.twig
<form method="post" action="{{ path('app_salles_delete', {'id': salle.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ salle.id) }}">
    <button class="btn">Delete</button>
</form>

templates/salles/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/salles/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Salles{% endblock %}

{% block body %}
    <h1>Edit Salles</h1>

    {{ include('salles/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_salles_index') }}">back to list</a>

    {{ include('salles/_delete_form.html.twig') }}
{% endblock %}

templates/salles/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salles index
{% endblock %}

{% block body %}
	<h1>Salles index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Cinema</th>
				<th>Qualite_projection</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for salle in salles %}
				<tr>
					<td>{{ salle.id }}</td>
					<td>{{ salle.id_cinema.nomCinema }}</td>
					<td>{{ salle.qualiteProjection }}</td>

					<td>
						<a href="{{ path('app_salles_show', {'id': salle.id}) }}">show</a>
						<a href="{{ path('app_salles_edit', {'id': salle.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="4">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_salles_new') }}">Create new</a>
{% endblock %}

templates/salles/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Salles{% endblock %}

{% block body %}
    <h1>Create new Salles</h1>

    {{ include('salles/_form.html.twig') }}

    <a href="{{ path('app_salles_index') }}">back to list</a>
{% endblock %}

templates/salles/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Salles{% endblock %}

{% block body %}
    <h1>Salles</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ salle.id }}</td>
            </tr>
            <tr>
                <th>Qualite_projection</th>
                <td>{{ salle.qualiteProjection }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_salles_index') }}">back to list</a>

    <a href="{{ path('app_salles_edit', {'id': salle.id}) }}">edit</a>

    {{ include('salles/_delete_form.html.twig') }}
{% endblock %}